global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "hotel_booking_metrics"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["hotel-booking:8080"]